  Dalfox:
    if: always()
    runs-on: ubuntu-latest
    needs: [URL-Enumeration, KXSS-Enum]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: url-collector-artifacts         
      - name: Dalfox
        run: |
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/dalfox-xss.sh xss-params.txt "$XSS_HUNTER"      
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK"
          if [[ -f xss-urls.txt ]] ; then curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-XSS-URL -F file=@xss-urls.txt; fi
